import { useState } from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';

export default function Work() {
  const [image, setImage] = useState('/assets/projects/project-neotek-1.png');

  const projects = [
    {
      id: 'youthcall',
      heading: 'YouthCall',
      link: 'https://youthcall.mk',
      description: `YouthCall aims to assist young individuals in discovering suitable projects, courses, activities, or volunteering opportunities. For this project, I had to engineer a platform using NodeJS with ExpressJS for the backend, React for the frontend, ensuring fast and easy-to-use user experience, and MongoDB as database.`,
      year: '2023',
      language: 'Macedonian',
      jobRole: 'Web Developer / UX/UI Designer',
      technologies: ['React', 'NodeJS', 'ExpressJS', 'MongoDB', 'Figma'],
      images: [
        '/assets/projects/project-youthcall-1.png',
        '/assets/projects/project-youthcall-2.png',
        '/assets/projects/project-youthcall-3.png',
        '/assets/projects/project-youthcall-4.png',
        '/assets/projects/project-youthcall-5.png',
      ],
    },
    {
      id: 'neotek-systems',
      heading: 'Neotek Systems',
      link: 'https://neotek.mk',
      description: `Neotek Systems, a company based in Strumica specializing in powder coatings. The website's aim was to enhance the company's online visibility and attract more customers to their services.`,
      year: '2024',
      language: 'Macedonian / Albanian',
      jobRole: 'Web Developer / UX/UI Designer',
      technologies: ['HTML', 'CSS', 'JavaScript', 'SwiperJS'],
      images: [
        '/assets/projects/project-neotek-1.png',
        '/assets/projects/project-neotek-2.png',
        '/assets/projects/project-neotek-3.png',
        '/assets/projects/project-neotek-4.png',
      ],
    },
    {
      id: 'dkseticom',
      heading: 'DKSeticom',
      description: `DKSeticom is a fictional company designed to showcase my modern web design skills. This project features a user-friendly SaaS platform website that unifies various communication tools. All texts, including headlines and testimonials, are generated by ChatGPT. This design highlights clean aesthetics and intuitive navigation, reflecting my expertise in crafting professional and engaging websites.`,
      year: '2024',
      language: 'English',
      jobRole: 'UX/UI Designer',
      technologies: ['Figma'],
      images: [
        '/assets/projects/project-dkseticom-1.png',
        '/assets/projects/project-dkseticom-2.png',
        '/assets/projects/project-dkseticom-3.png',
        '/assets/projects/project-dkseticom-4.png',
      ],
    },

    {
      id: 'personal-portfolio',
      heading: 'Personal Portfolio',
      description: `Personal portfolio for Dimitar Kalapocev (me) developed to showcase my skills in design & development. On this portfolio you can find information about me, my projects, my location (and some info about the location) and availability status. While this portfolio is still a work in progress, feel free to interrupt me for your project!`,
      year: '2024',
      language: 'English',
      jobRole: 'Web Developer / UX/UI Designer',
      technologies: ['React', 'Figma'],
      images: [
        '/assets/projects/project-personal-portfolio-1.png',
        '/assets/projects/project-personal-portfolio-2.png',
        '/assets/projects/project-personal-portfolio-3.png',
      ],
    },
    {
      id: 'strax-designs',
      heading: 'Strax Designs',
      description: `Strax Designs, co-founded by me, aimed to assist businesses in their digital shift. We leveraged our web development expertise to help businesses bring their products/services online, making them accessible to a wider audience.`,
      year: '2023',
      language: 'English',
      jobRole: 'Web Developer / UX/UI Designer / Co-Founder',
      technologies: ['HTML', 'CSS', 'JavaScript', 'NodeJS', 'MongoDB', 'Figma'],
      images: [
        '/assets/projects/project-strax-designs-1.png',
        '/assets/projects/project-strax-designs-2.png',
        '/assets/projects/project-strax-designs-3.png',
        '/assets/projects/project-strax-designs-4.png',
        '/assets/projects/project-strax-designs-5.png',
        '/assets/projects/project-strax-designs-6.png',
        '/assets/projects/project-strax-designs-7.png',
        '/assets/projects/project-strax-designs-8.png',
      ],
    },
    {
      id: 'forkify',
      heading: 'Forkify',
      link: 'https://dk-forkify.netlify.app/',
      description: `Forkify, project from a JavaScript course by Jonas Schmedtmann, puts our learned skills to the test. It covers OOP JavaScript, asynchronous JavaScript, APIs, and various practical JavaScript methods. The app offers food recipes, allowing users to search, bookmark favorites, and add new recipes.`,
      year: '2022',
      language: 'English',
      jobRole: 'Web Developer',
      technologies: ['JavaScript'],
      images: [
        '/assets/projects/project-forkify-1.png',
        '/assets/projects/project-forkify-2.png',
        '/assets/projects/project-forkify-3.png',
        '/assets/projects/project-forkify-4.png',
        '/assets/projects/project-forkify-5.png',
      ],
    },
    {
      id: 'personal-web-app',
      heading: 'Personal Web App',
      description: `Personal Web App designed with modern simplistic UI aiming to help you with personal notes, reminders, money management and tracking your personal goals. The design includes login & register system, as well as customization for the color palette and currency. Disclaimer: this project is currently only design.`,
      year: '2024',
      language: 'English',
      jobRole: 'UX/UI Designer',
      technologies: ['Figma'],
      images: [
        '/assets/projects/project-personal-web-app-1.png',
        '/assets/projects/project-personal-web-app-2.png',
        '/assets/projects/project-personal-web-app-3.png',
        '/assets/projects/project-personal-web-app-4.png',
      ],
    },
  ];

  const container = {
    hidden: { opacity: 1, scale: 0 },
    visible: {
      opacity: 1,
      scale: 1,
      transition: {
        delayChildren: 0.1,
        staggerChildren: 0.15,
      },
    },
  };

  const item = {
    hidden: { y: 20, opacity: 0 },
    visible: {
      y: 0,
      opacity: 1,
    },
  };

  return (
    <div data-scroll-section>
      <div className="container container__padding-block">
        <motion.h1
          className="projects-heading"
          initial={{ opacity: 0, scale: 0.5 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{
            duration: 1,
            ease: 'anticipate',
          }}
        >
          Explore the fine selection of projects
        </motion.h1>

        <div className="project-container">
          <motion.ul
            className="projects"
            variants={container}
            initial="hidden"
            animate="visible"
          >
            {projects.map((project) => (
              <motion.li
                key={project.id}
                variants={item}
                className="h2 projects__heading"
              >
                <Link
                  to={`/work/${project.id}`}
                  state={{ projectData: project }}
                  onMouseOver={() => setImage(project.images[0])}
                >
                  {project.heading}
                </Link>
              </motion.li>
            ))}

            <motion.img
              className="projects__image-showcase"
              variants={item}
              src={image}
            />
          </motion.ul>
        </div>
      </div>
    </div>
  );
}
